version = 1

test_patterns = ["*Tests/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["qrAPI/Dockerfile"]
