language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/qrAPI.Tests/qrAPI.Tests.csproj
  - dotnet test src/qrAPI.App.Tests/qrAPI.App.Tests.csproj
  - dotnet test src/qrAPI.DAL.Tests/qrAPI.DAL.Tests.csproj
  - dotnet test src/qrAPI.Web.Tests/qrAPI.Web.Tests.csproj
