version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  qr-api:
    build: 
      context: .
      dockerfile: qrAPI/Dockerfile
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - MemoryCacheSettings__ConnectionString=${MemoryCacheSettings__ConnectionString}
      - MemoryCacheSettings__Enabled=${MemoryCacheSettings__Enabled}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - JwtOptions__Secret=${JwtOptions__Secret}
    ports:
      - "7000:80"
    depends_on:
      - db-server
      - redis
    networks:
      - localdev
        
  db-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev