### YamlMime:ManagedReference
items:
- uid: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider
  commentId: T:qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider
  id: CreateQrRequestExampleProvider
  parent: qrAPI.Swagger.Examples.Requests.Create
  children:
  - qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples
  langs:
  - csharp
  - vb
  name: CreateQrRequestExampleProvider
  nameWithType: CreateQrRequestExampleProvider
  fullName: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider
  type: Class
  source:
    remote:
      path: src/qrAPI/Swagger/Examples/Requests/Create/CreateQrRequestExampleProvider.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: CreateQrRequestExampleProvider
    path: ../src/qrAPI/Swagger/Examples/Requests/Create/CreateQrRequestExampleProvider.cs
    startLine: 6
  assemblies:
  - qrAPI
  namespace: qrAPI.Swagger.Examples.Requests.Create
  syntax:
    content: 'public class CreateQrRequestExampleProvider : IExamplesProvider<CreateQrRequest>'
    content.vb: >-
      Public Class CreateQrRequestExampleProvider
          Implements IExamplesProvider(Of CreateQrRequest)
  inheritance:
  - System.Object
  implements:
  - Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples
  commentId: M:qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples
  id: GetExamples
  parent: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider
  langs:
  - csharp
  - vb
  name: GetExamples()
  nameWithType: CreateQrRequestExampleProvider.GetExamples()
  fullName: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples()
  type: Method
  source:
    remote:
      path: src/qrAPI/Swagger/Examples/Requests/Create/CreateQrRequestExampleProvider.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: GetExamples
    path: ../src/qrAPI/Swagger/Examples/Requests/Create/CreateQrRequestExampleProvider.cs
    startLine: 8
  assemblies:
  - qrAPI
  namespace: qrAPI.Swagger.Examples.Requests.Create
  syntax:
    content: public CreateQrRequest GetExamples()
    return:
      type: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
    content.vb: Public Function GetExamples As CreateQrRequest
  overload: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples*
  implements:
  - Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}.GetExamples
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: qrAPI.Swagger.Examples.Requests.Create
  commentId: N:qrAPI.Swagger.Examples.Requests.Create
  name: qrAPI.Swagger.Examples.Requests.Create
  nameWithType: qrAPI.Swagger.Examples.Requests.Create
  fullName: qrAPI.Swagger.Examples.Requests.Create
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}
  commentId: T:Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}
  parent: Swashbuckle.AspNetCore.Filters
  definition: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  name: IExamplesProvider<CreateQrRequest>
  nameWithType: IExamplesProvider<CreateQrRequest>
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<qrAPI.Contracts.v1.Requests.Create.CreateQrRequest>
  nameWithType.vb: IExamplesProvider(Of CreateQrRequest)
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of qrAPI.Contracts.v1.Requests.Create.CreateQrRequest)
  name.vb: IExamplesProvider(Of CreateQrRequest)
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    nameWithType: IExamplesProvider
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
    name: CreateQrRequest
    nameWithType: CreateQrRequest
    fullName: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    nameWithType: IExamplesProvider
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
    name: CreateQrRequest
    nameWithType: CreateQrRequest
    fullName: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  commentId: T:Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  isExternal: true
  name: IExamplesProvider<T>
  nameWithType: IExamplesProvider<T>
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<T>
  nameWithType.vb: IExamplesProvider(Of T)
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of T)
  name.vb: IExamplesProvider(Of T)
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    nameWithType: IExamplesProvider
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    nameWithType: IExamplesProvider
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Swashbuckle.AspNetCore.Filters
  commentId: N:Swashbuckle.AspNetCore.Filters
  isExternal: true
  name: Swashbuckle.AspNetCore.Filters
  nameWithType: Swashbuckle.AspNetCore.Filters
  fullName: Swashbuckle.AspNetCore.Filters
- uid: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples*
  commentId: Overload:qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples
  name: GetExamples
  nameWithType: CreateQrRequestExampleProvider.GetExamples
  fullName: qrAPI.Swagger.Examples.Requests.Create.CreateQrRequestExampleProvider.GetExamples
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}.GetExamples
  commentId: M:Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}.GetExamples
  parent: Swashbuckle.AspNetCore.Filters.IExamplesProvider{qrAPI.Contracts.v1.Requests.Create.CreateQrRequest}
  definition: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  name: GetExamples()
  nameWithType: IExamplesProvider<CreateQrRequest>.GetExamples()
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<qrAPI.Contracts.v1.Requests.Create.CreateQrRequest>.GetExamples()
  nameWithType.vb: IExamplesProvider(Of CreateQrRequest).GetExamples()
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of qrAPI.Contracts.v1.Requests.Create.CreateQrRequest).GetExamples()
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    nameWithType: IExamplesProvider<CreateQrRequest>.GetExamples
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<qrAPI.Contracts.v1.Requests.Create.CreateQrRequest>.GetExamples
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    nameWithType: IExamplesProvider(Of CreateQrRequest).GetExamples
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of qrAPI.Contracts.v1.Requests.Create.CreateQrRequest).GetExamples
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
  commentId: T:qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
  parent: qrAPI.Contracts.v1.Requests.Create
  name: CreateQrRequest
  nameWithType: CreateQrRequest
  fullName: qrAPI.Contracts.v1.Requests.Create.CreateQrRequest
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  commentId: M:Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  isExternal: true
  name: GetExamples()
  nameWithType: IExamplesProvider<T>.GetExamples()
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<T>.GetExamples()
  nameWithType.vb: IExamplesProvider(Of T).GetExamples()
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of T).GetExamples()
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    nameWithType: IExamplesProvider<T>.GetExamples
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<T>.GetExamples
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    nameWithType: IExamplesProvider(Of T).GetExamples
    fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of T).GetExamples
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: qrAPI.Contracts.v1.Requests.Create
  commentId: N:qrAPI.Contracts.v1.Requests.Create
  name: qrAPI.Contracts.v1.Requests.Create
  nameWithType: qrAPI.Contracts.v1.Requests.Create
  fullName: qrAPI.Contracts.v1.Requests.Create
