### YamlMime:ManagedReference
items:
- uid: qrAPI.Infra.Settings.MemoryCacheSettings
  commentId: T:qrAPI.Infra.Settings.MemoryCacheSettings
  id: MemoryCacheSettings
  parent: qrAPI.Infra.Settings
  children:
  - qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
  - qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
  - qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
  - qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
  langs:
  - csharp
  - vb
  name: MemoryCacheSettings
  nameWithType: MemoryCacheSettings
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings
  type: Class
  source:
    remote:
      path: src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: MemoryCacheSettings
    path: ../../QrApi/src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
    startLine: 4
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Settings
  syntax:
    content: public class MemoryCacheSettings
    content.vb: Public Class MemoryCacheSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
  commentId: P:qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
  id: Enabled
  parent: qrAPI.Infra.Settings.MemoryCacheSettings
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: MemoryCacheSettings.Enabled
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: Enabled
    path: ../../QrApi/src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
    startLine: 6
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Settings
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: qrAPI.Infra.Settings.MemoryCacheSettings.Enabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
  commentId: P:qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
  id: ConnectionString
  parent: qrAPI.Infra.Settings.MemoryCacheSettings
  langs:
  - csharp
  - vb
  name: ConnectionString
  nameWithType: MemoryCacheSettings.ConnectionString
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: ConnectionString
    path: ../../QrApi/src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
    startLine: 7
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Settings
  syntax:
    content: public string ConnectionString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConnectionString As String
  overload: qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
  commentId: P:qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
  id: AbsoluteExpirationHours
  parent: qrAPI.Infra.Settings.MemoryCacheSettings
  langs:
  - csharp
  - vb
  name: AbsoluteExpirationHours
  nameWithType: MemoryCacheSettings.AbsoluteExpirationHours
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: AbsoluteExpirationHours
    path: ../../QrApi/src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
    startLine: 8
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Settings
  syntax:
    content: public TimeSpan AbsoluteExpirationHours { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property AbsoluteExpirationHours As TimeSpan
  overload: qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
  commentId: P:qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
  id: SlidingExpiration
  parent: qrAPI.Infra.Settings.MemoryCacheSettings
  langs:
  - csharp
  - vb
  name: SlidingExpiration
  nameWithType: MemoryCacheSettings.SlidingExpiration
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: SlidingExpiration
    path: ../../QrApi/src/qrAPI.Infra/Settings/MemoryCacheSettings.cs
    startLine: 9
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Settings
  syntax:
    content: public TimeSpan SlidingExpiration { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property SlidingExpiration As TimeSpan
  overload: qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: qrAPI.Infra.Settings
  commentId: N:qrAPI.Infra.Settings
  name: qrAPI.Infra.Settings
  nameWithType: qrAPI.Infra.Settings
  fullName: qrAPI.Infra.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.Enabled*
  commentId: Overload:qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
  name: Enabled
  nameWithType: MemoryCacheSettings.Enabled
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString*
  commentId: Overload:qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
  name: ConnectionString
  nameWithType: MemoryCacheSettings.ConnectionString
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.ConnectionString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours*
  commentId: Overload:qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
  name: AbsoluteExpirationHours
  nameWithType: MemoryCacheSettings.AbsoluteExpirationHours
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.AbsoluteExpirationHours
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration*
  commentId: Overload:qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
  name: SlidingExpiration
  nameWithType: MemoryCacheSettings.SlidingExpiration
  fullName: qrAPI.Infra.Settings.MemoryCacheSettings.SlidingExpiration
