### YamlMime:ManagedReference
items:
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings
  commentId: T:qrAPI.Infra.Mail.TestMail.TestMailSettings
  id: TestMailSettings
  parent: qrAPI.Infra.Mail.TestMail
  children:
  - qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
  - qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
  - qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
  - qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
  langs:
  - csharp
  - vb
  name: TestMailSettings
  nameWithType: TestMailSettings
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings
  type: Class
  source:
    remote:
      path: src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: TestMailSettings
    path: ../src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
    startLine: 2
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Mail.TestMail
  syntax:
    content: public class TestMailSettings
    content.vb: Public Class TestMailSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
  commentId: P:qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
  id: ApiKey
  parent: qrAPI.Infra.Mail.TestMail.TestMailSettings
  langs:
  - csharp
  - vb
  name: ApiKey
  nameWithType: TestMailSettings.ApiKey
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: ApiKey
    path: ../src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
    startLine: 4
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Mail.TestMail
  syntax:
    content: public string ApiKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApiKey As String
  overload: qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
  commentId: P:qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
  id: Namespace
  parent: qrAPI.Infra.Mail.TestMail.TestMailSettings
  langs:
  - csharp
  - vb
  name: Namespace
  nameWithType: TestMailSettings.Namespace
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: Namespace
    path: ../src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
    startLine: 5
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Mail.TestMail
  syntax:
    content: public string Namespace { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Namespace As String
  overload: qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
  commentId: P:qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
  id: BaseUrl
  parent: qrAPI.Infra.Mail.TestMail.TestMailSettings
  langs:
  - csharp
  - vb
  name: BaseUrl
  nameWithType: TestMailSettings.BaseUrl
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: BaseUrl
    path: ../src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
    startLine: 6
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Mail.TestMail
  syntax:
    content: public string BaseUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BaseUrl As String
  overload: qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
  commentId: P:qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
  id: TestMail
  parent: qrAPI.Infra.Mail.TestMail.TestMailSettings
  langs:
  - csharp
  - vb
  name: TestMail
  nameWithType: TestMailSettings.TestMail
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
  type: Property
  source:
    remote:
      path: src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
      branch: master
      repo: https://github.com/facundo91/QrApi.git
    id: TestMail
    path: ../src/qrAPI.Infra/Mail/TestMail/TestMailSettings.cs
    startLine: 7
  assemblies:
  - qrAPI.Infra
  namespace: qrAPI.Infra.Mail.TestMail
  syntax:
    content: public string TestMail { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TestMail As String
  overload: qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: qrAPI.Infra.Mail.TestMail
  commentId: N:qrAPI.Infra.Mail.TestMail
  name: qrAPI.Infra.Mail.TestMail
  nameWithType: qrAPI.Infra.Mail.TestMail
  fullName: qrAPI.Infra.Mail.TestMail
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey*
  commentId: Overload:qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
  name: ApiKey
  nameWithType: TestMailSettings.ApiKey
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.ApiKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace*
  commentId: Overload:qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
  name: Namespace
  nameWithType: TestMailSettings.Namespace
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.Namespace
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl*
  commentId: Overload:qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
  name: BaseUrl
  nameWithType: TestMailSettings.BaseUrl
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.BaseUrl
- uid: qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail*
  commentId: Overload:qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
  name: TestMail
  nameWithType: TestMailSettings.TestMail
  fullName: qrAPI.Infra.Mail.TestMail.TestMailSettings.TestMail
